<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Understanding Exceptions</title>

    <link rel="alternate" href="https://campusempresa.com/python/understanding-exceptions" hreflang="es" />
	<link rel="alternate" href="https://campusempresa.cat/python/understanding-exceptions" hreflang="ca" />
	<link rel="alternate" href="https://enterprisecampus.net/python/understanding-exceptions" hreflang="en" />
    
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
	<link href="/css/site.css" rel="stylesheet">
	
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
  	<script type="text/javascript" src="js/math_init.js"></script>
  	<script type="text/javascript" id="MathJax-script" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/startup.js"></script>
  	<script type="text/javascript" src="/js/cookie.js"></script>
  	<script type="text/javascript" src="/js/main.js"></script>
</head>

<body>
    <div id="content">
		<div id="header" class="container-xxl">
	<div class="row">
		<div class="col-8 p-0">
			<h1 class="m-0 p-0">
				<a href="/"><img src="/img/logo_header.png" style="visibility:hiddenxx;"></a>
			</h1>
		</div>
		<div class="col-4 p-0 text-end">
			<h2 id="main_title"><cite>Building today's and tomorrow's society</cite></h2>
			<h3 id="main_subtitle"></h3>
		</div>
	</div>
</div>
<div class="container-xxl" style="margin-top: -1em;">
	<div class="row">
		<div class="col-12 p-0 m-0 text-end">
													<b id="lit_lang_es" class="px-2">EN</b>
				|
				<a href="https://campusempresa.com/python/understanding-exceptions" class="px-2">ES</a></b>
				|
				<a href="https://campusempresa.cat/python/understanding-exceptions" class="px-2">CA</a>
					</div>
	</div>
</div>
   <div class="top-bar container-fluid">
	<div class="container-xxl">
		<div class="row">
			<div class="col" id="left_menu">
				<a href="/objective">The Project</a>
				<a href="/about">About Us</a>
				<a href="/contribute">Contribute</a>
				<a href="/donate">Donations</a>
				<a href="/licence">License</a>
			</div>
		</div>
	</div>
   </div>

<div class="container-xxl" id="main_content">
	<div class="row">
		<div class="col-12 col-lg-8">
			<div id="nav1" class="navigation"></div>
			<div id="inner_content"><div class='row navigation'>
	<div class='col-4'>
					<a href='file-and-directory-operations'>&#x25C4;File and Directory Operations</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Understanding Exceptions</a>
	</div>
	<div class='col-4 text-end'>
					<a href='handling-exceptions'>Handling Exceptions &#x25BA;</a>
			</div>
</div>
<div class='content'></div><h1>Introduction to Exceptions</h1>
<div class='content'><p>Exceptions are events that can alter the normal flow of a program. They are typically used to handle errors or other exceptional conditions that occur during the execution of a program.</p>
</div><h2>Key Concepts</h2>
<div class='content'><ul>
<li><strong>Exception</strong>: An error that occurs during the execution of a program.</li>
<li><strong>Exception Handling</strong>: The process of responding to exceptions when they occur.</li>
<li><strong>Try Block</strong>: A block of code that is tested for errors while it is being executed.</li>
<li><strong>Except Block</strong>: A block of code that is executed if an error occurs in the try block.</li>
<li><strong>Finally Block</strong>: A block of code that is executed regardless of whether an exception occurs or not.</li>
</ul>
</div><h1>Basic Exception Handling</h1>
<div class='content'><p>In Python, exceptions are handled using the <code>try</code>, <code>except</code>, and optionally <code>finally</code> blocks.</p>
</div><h2>Example</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("dHJ5OgogICAgIyBDb2RlIHRoYXQgbWF5IHJhaXNlIGFuIGV4Y2VwdGlvbgogICAgcmVzdWx0ID0gMTAgLyAwCmV4Y2VwdCBaZXJvRGl2aXNpb25FcnJvcjoKICAgICMgQ29kZSB0byBoYW5kbGUgdGhlIGV4Y2VwdGlvbgogICAgcHJpbnQoIkNhbm5vdCBkaXZpZGUgYnkgemVybyEiKQpmaW5hbGx5OgogICAgIyBDb2RlIHRoYXQgd2lsbCBydW4gbm8gbWF0dGVyIHdoYXQKICAgIHByaW50KCJFeGVjdXRpb24gY29tcGxldGVkLiIp"))));alert("Copied!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>try:
    # Code that may raise an exception
    result = 10 / 0
except ZeroDivisionError:
    # Code to handle the exception
    print(&quot;Cannot divide by zero!&quot;)
finally:
    # Code that will run no matter what
    print(&quot;Execution completed.&quot;)</pre></div><div class='content'></div><h2>Explanation</h2>
<div class='content'><ul>
<li>The <code>try</code> block contains code that might throw an exception.</li>
<li>The <code>except</code> block catches and handles the exception.</li>
<li>The <code>finally</code> block contains code that will always execute, regardless of whether an exception was raised or not.</li>
</ul>
</div><h1>Handling Multiple Exceptions</h1>
<div class='content'><p>You can handle multiple exceptions by specifying multiple <code>except</code> blocks.</p>
</div><h2>Example</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("dHJ5OgogICAgdmFsdWUgPSBpbnQoaW5wdXQoIkVudGVyIGEgbnVtYmVyOiAiKSkKICAgIHJlc3VsdCA9IDEwIC8gdmFsdWUKZXhjZXB0IFZhbHVlRXJyb3I6CiAgICBwcmludCgiSW52YWxpZCBpbnB1dCEgUGxlYXNlIGVudGVyIGEgbnVtYmVyLiIpCmV4Y2VwdCBaZXJvRGl2aXNpb25FcnJvcjoKICAgIHByaW50KCJDYW5ub3QgZGl2aWRlIGJ5IHplcm8hIikKZmluYWxseToKICAgIHByaW50KCJFeGVjdXRpb24gY29tcGxldGVkLiIp"))));alert("Copied!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>try:
    value = int(input(&quot;Enter a number: &quot;))
    result = 10 / value
except ValueError:
    print(&quot;Invalid input! Please enter a number.&quot;)
except ZeroDivisionError:
    print(&quot;Cannot divide by zero!&quot;)
finally:
    print(&quot;Execution completed.&quot;)</pre></div><div class='content'></div><h2>Explanation</h2>
<div class='content'><ul>
<li>Multiple <code>except</code> blocks allow you to handle different types of exceptions separately.</li>
<li>This makes your code more robust and easier to debug.</li>
</ul>
</div><h1>Using Else with Try-Except</h1>
<div class='content'><p>The <code>else</code> block can be used to execute code if no exceptions are raised in the <code>try</code> block.</p>
</div><h2>Example</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("dHJ5OgogICAgdmFsdWUgPSBpbnQoaW5wdXQoIkVudGVyIGEgbnVtYmVyOiAiKSkKICAgIHJlc3VsdCA9IDEwIC8gdmFsdWUKZXhjZXB0IFplcm9EaXZpc2lvbkVycm9yOgogICAgcHJpbnQoIkNhbm5vdCBkaXZpZGUgYnkgemVybyEiKQplbHNlOgogICAgcHJpbnQoZiJSZXN1bHQgaXMge3Jlc3VsdH0iKQpmaW5hbGx5OgogICAgcHJpbnQoIkV4ZWN1dGlvbiBjb21wbGV0ZWQuIik="))));alert("Copied!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>try:
    value = int(input(&quot;Enter a number: &quot;))
    result = 10 / value
except ZeroDivisionError:
    print(&quot;Cannot divide by zero!&quot;)
else:
    print(f&quot;Result is {result}&quot;)
finally:
    print(&quot;Execution completed.&quot;)</pre></div><div class='content'></div><h2>Explanation</h2>
<div class='content'><ul>
<li>The <code>else</code> block runs only if the <code>try</code> block does not raise an exception.</li>
<li>This can be useful for code that should only run if no errors occurred.</li>
</ul>
</div><h1>Raising Exceptions</h1>
<div class='content'><p>You can raise exceptions using the <code>raise</code> keyword.</p>
</div><h2>Example</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("ZGVmIGNoZWNrX2FnZShhZ2UpOgogICAgaWYgYWdlIDwgMTg6CiAgICAgICAgcmFpc2UgVmFsdWVFcnJvcigiQWdlIG11c3QgYmUgYXQgbGVhc3QgMTguIikKICAgIHJldHVybiAiQWNjZXNzIGdyYW50ZWQuIgoKdHJ5OgogICAgcHJpbnQoY2hlY2tfYWdlKDE1KSkKZXhjZXB0IFZhbHVlRXJyb3IgYXMgZToKICAgIHByaW50KGUp"))));alert("Copied!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>def check_age(age):
    if age &lt; 18:
        raise ValueError(&quot;Age must be at least 18.&quot;)
    return &quot;Access granted.&quot;

try:
    print(check_age(15))
except ValueError as e:
    print(e)</pre></div><div class='content'></div><h2>Explanation</h2>
<div class='content'><ul>
<li>The <code>raise</code> keyword is used to manually trigger an exception.</li>
<li>This can be useful for enforcing certain conditions in your code.</li>
</ul>
</div><h1>Custom Exceptions</h1>
<div class='content'><p>You can define your own exceptions by creating a new class that inherits from the built-in <code>Exception</code> class.</p>
</div><h2>Example</h2>
<div style='position:relative'><a class='copy_button' href='#' onclick='navigator.clipboard.writeText(decodeURIComponent(escape(atob("Y2xhc3MgQ3VzdG9tRXJyb3IoRXhjZXB0aW9uKToKICAgIHBhc3MKCmRlZiBjaGVja192YWx1ZSh2YWx1ZSk6CiAgICBpZiB2YWx1ZSA8IDA6CiAgICAgICAgcmFpc2UgQ3VzdG9tRXJyb3IoIlZhbHVlIGNhbm5vdCBiZSBuZWdhdGl2ZS4iKQogICAgcmV0dXJuIHZhbHVlCgp0cnk6CiAgICBwcmludChjaGVja192YWx1ZSgtNSkpCmV4Y2VwdCBDdXN0b21FcnJvciBhcyBlOgogICAgcHJpbnQoZSk="))));alert("Copied!");return false;'><i class='bi bi-copy'></i></a><pre class='code'>class CustomError(Exception):
    pass

def check_value(value):
    if value &lt; 0:
        raise CustomError(&quot;Value cannot be negative.&quot;)
    return value

try:
    print(check_value(-5))
except CustomError as e:
    print(e)</pre></div><div class='content'></div><h2>Explanation</h2>
<div class='content'><ul>
<li>Custom exceptions allow you to create more specific error messages and handling routines.</li>
<li>This can make your code more readable and maintainable.</li>
</ul>
</div><h1>Summary</h1>
<div class='content'><ul>
<li>Exceptions are used to handle errors and other exceptional conditions in a program.</li>
<li>The <code>try</code>, <code>except</code>, and <code>finally</code> blocks are used to handle exceptions.</li>
<li>Multiple exceptions can be handled using multiple <code>except</code> blocks.</li>
<li>The <code>else</code> block can be used to execute code if no exceptions are raised.</li>
<li>Exceptions can be manually raised using the <code>raise</code> keyword.</li>
<li>Custom exceptions can be created by defining new classes that inherit from the <code>Exception</code> class.</li>
</ul>
<p>Understanding and effectively using exceptions is crucial for writing robust and error-resistant Python programs.</p>
</div><div class='row navigation'>
	<div class='col-4'>
					<a href='file-and-directory-operations'>&#x25C4;File and Directory Operations</a>
			</div>
	<div class='col-4 text-center'>
		<a href="./" class="title">Understanding Exceptions</a>
	</div>
	<div class='col-4 text-end'>
					<a href='handling-exceptions'>Handling Exceptions &#x25BA;</a>
			</div>
</div>
</div>
		</div>
		<div class="col-12 col-lg-4 publi" id="div_publi">
			<h1>Advertising</h1>
			<p>This space is reserved for advertising.</p>
			<p>If you want to be a sponsor, contact us to include links in this area: <a href='mailto:admin@campusempresa.cat'>admin@campusempresa.cat</a></p>
			<p>Thank you for collaborating!</p>
		</div>
	</div>
</div>

   <div class="container-xxl my-3">
	<div class="row">
		<div class="col">
			<footer>&copy; Copyright 2024. All rights reserved</footer>
		</div>
	</div>
</div>	

<div id="cookies_adv" style="display:none;">
	Fem servir galetes per millorar la teva experiència d'ús i oferir continguts adaptats als teus interessos
    <a href="#" id="btn_accept_cookies" class="button">Entès!</a>
    <a href="/cookies">Més informació</a>
</div>	

	</div>    
</body>
</html>
